#!/usr/bin/env bash
set -euo pipefail

# Symlinks this repository's skills and scripts into the Claude Code user
# directory, matching how the ~/.agents/skills entries are already wired.
# Re-runnable: an existing correct link is left alone, a wrong one is replaced,
# and a real directory is refused rather than silently destroyed.

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"

# Windows refuses symlinks without Developer Mode or elevation, but allows
# directory junctions and file hardlinks to any user. Detect once.
readonly IS_WINDOWS=$([[ "$(uname -s)" == MINGW* || "$(uname -s)" == MSYS* ]] && echo 1 || echo 0)

# Identifies a launcher this script generated, so a regenerated one is replaced
# rather than refused, while a stranger's file at the same path is left alone.
readonly LAUNCHER_MARKER='claude-harness:launcher'

make_link() {
  local src="$1" dest="$2"

  # Scripts get a launcher, not a link. A hardlink breaks the moment an editor
  # rewrites the repository copy instead of modifying it in place, and the
  # stale installed copy then runs silently. A launcher cannot go stale.
  if [[ -f "$src" ]]; then
    local target
    if [[ "$IS_WINDOWS" -eq 1 ]]; then target=$(cygpath -w "$src"); else target="$src"; fi
    cat > "$dest" <<LAUNCHER
#!/usr/bin/env node
// $LAUNCHER_MARKER
// Generated by claude-harness/install.sh. Do not edit; edit the repository copy.
import { spawnSync } from "node:child_process";
const r = spawnSync(process.execPath, [String.raw\`$target\`, ...process.argv.slice(2)], { stdio: "inherit" });
process.exit(r.status ?? 1);
LAUNCHER
    return
  fi

  if [[ "$IS_WINDOWS" -eq 1 ]]; then
    # `cmd //c mklink` mangles paths under Git Bash and fails silently.
    # PowerShell's New-Item takes real Windows paths and works unelevated.
    local win_src win_dest
    win_src=$(cygpath -w "$src")
    win_dest=$(cygpath -w "$dest")
    powershell -NoProfile -NonInteractive -Command \
      "New-Item -ItemType Junction -Path '$win_dest' -Target '$win_src' -ErrorAction Stop | Out-Null" \
      >/dev/null 2>&1
    return
  fi

  ln -s "$src" "$dest"
}

# A junction reports as a directory, not a link, so -L is not enough to tell an
# already-installed entry from a stray copy. Compare identity instead.
already_linked() {
  local src="$1" dest="$2"
  # A junction resolves to the target's contents, so identity is the test.
  [[ -d "$src" && -d "$dest" ]] && [[ "$dest" -ef "$src" ]] && return 0
  [[ -L "$dest" ]] && [[ "$(readlink "$dest")" == "$src" ]] && return 0
  return 1
}

# Ours to replace: a launcher this script wrote, whatever version.
is_our_launcher() {
  [[ -f "$1" ]] && grep -q "$LAUNCHER_MARKER" "$1" 2>/dev/null
}

link_one() {
  local src="$1" dest="$2" name
  name=$(basename "$dest")

  if already_linked "$src" "$dest"; then
    printf '  ok       %s\n' "$name"
    return 0
  fi

  if [[ -L "$dest" ]] || is_our_launcher "$dest"; then
    rm -f "$dest"
  elif [[ -e "$dest" ]]; then
    # A real file or directory here is either the pre-repo copy or someone
    # else's work. Refuse rather than guess which.
    printf '  REFUSED  %s (exists and is not a link; move it aside first)\n' \
      "$name" >&2
    return 1
  fi

  if ! make_link "$src" "$dest"; then
    printf '  FAILED   %s (could not link)\n' "$name" >&2
    return 1
  fi

  # Verify rather than trust the exit status: mklink has been known to report
  # success on a link that is not there.
  if [[ ! -e "$dest" ]]; then
    printf '  FAILED   %s (link reported success but does not exist)\n' "$name" >&2
    return 1
  fi

  printf '  linked   %s\n' "$name"
}

main() {
  local failed=0

  printf 'skills -> %s/skills\n' "$CLAUDE_DIR"
  mkdir -p "$CLAUDE_DIR/skills"
  for skill in "$REPO_ROOT"/skills/*/; do
    [[ -d "$skill" ]] || continue
    skill="${skill%/}"
    link_one "$skill" "$CLAUDE_DIR/skills/$(basename "$skill")" || failed=1
  done

  printf 'scripts -> %s/scripts\n' "$CLAUDE_DIR"
  mkdir -p "$CLAUDE_DIR/scripts"
  for script in "$REPO_ROOT"/scripts/*; do
    [[ -f "$script" ]] || continue
    link_one "$script" "$CLAUDE_DIR/scripts/$(basename "$script")" || failed=1
  done

  if [[ "$failed" -ne 0 ]]; then
    printf '\nSome links were refused. Nothing was destroyed.\n' >&2
    return 1
  fi
  printf '\nDone.\n'
}

main "$@"
