#!/usr/bin/env node
// Points the Railly skills' canonical source root at the project being worked
// on, so contracts, cases and gate runs version with the code instead of
// living in a global checkout.
//
//   node scripts/railly-inrepo.mjs scaffold [project]
//
// Railly's resolver reads RAILLY_SKILLS_REPO before any default and validates
// three markers at the target. Creating the markers and setting the variable
// in the project's settings.local.json is the whole mechanism: his repository
// is never modified, so plugin updates land untouched.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

const MARKETPLACE_CLONE = join(homedir(), ".claude", "plugins", "marketplaces", "railly-skills");

const KNOWLEDGE_DIRS = [
	"foundry/missions",
	"foundry/knowledge/patterns",
	"foundry/knowledge/skills",
	"foundry/runs/solution-gate",
	"foundry/runs/review-gate",
	"foundry/runs/spec",
	"cases",
	"contracts",
	".claude-plugin",
	"scripts",
];

function scaffold(projectRoot) {
	const root = resolve(projectRoot);
	const base = join(root, ".claude", "knowledge");

	// git does not version empty directories, and these must survive a clean
	// clone so the skills write where they should without a re-scaffold.
	for (const d of KNOWLEDGE_DIRS) {
		mkdirSync(join(base, d), { recursive: true });
		const keep = join(base, d, ".gitkeep");
		if (!existsSync(keep)) writeFileSync(keep, "");
	}

	// The three markers resolve-source-root.mjs validates. No absolute paths:
	// this is versioned with the project and must resolve on any machine.
	const maturity = join(base, "foundry", "maturity.json");
	if (!existsSync(maturity)) {
		writeFileSync(maturity, `${JSON.stringify({ source: "railly-skills", mode: "in-repo" }, null, 2)}\n`);
	}
	const marketplace = join(base, ".claude-plugin", "marketplace.json");
	if (!existsSync(marketplace)) {
		writeFileSync(
			marketplace,
			`${JSON.stringify({ name: "railly-skills-inrepo", owner: { name: "local" }, plugins: [] }, null, 2)}\n`,
		);
	}

	// The skills look for <root>/scripts/work-item.mjs. The shim re-exports the
	// canonical copy at runtime instead of forking it, and resolves the clone
	// from the home directory so the project stays portable.
	for (const script of ["work-item.mjs", "resolve-source-root.mjs"]) {
		writeFileSync(
			join(base, "scripts", script),
			[
				"#!/usr/bin/env node",
				"// shim -> canonical railly-skills clone (generated by claude-harness/scripts/railly-inrepo.mjs)",
				'import { spawnSync } from "node:child_process";',
				'import { homedir } from "node:os";',
				'import { join } from "node:path";',
				`const target = join(homedir(), ".claude", "plugins", "marketplaces", "railly-skills", "scripts", ${JSON.stringify(script)});`,
				'const r = spawnSync(process.execPath, [target, ...process.argv.slice(2)], { stdio: "inherit" });',
				"process.exit(r.status ?? 1);",
				"",
			].join("\n"),
		);
	}

	// Settings `env` values are literal strings, so the path is absolute; that
	// is why it lives in settings.local.json, per machine and gitignored.
	const settingsPath = join(root, ".claude", "settings.local.json");
	let settings = {};
	if (existsSync(settingsPath)) {
		try {
			settings = JSON.parse(readFileSync(settingsPath, "utf8"));
		} catch {
			console.error(`settings.local.json exists but is not valid JSON; left untouched: ${settingsPath}`);
			settings = null;
		}
	}
	if (settings) {
		settings.env = { ...(settings.env || {}), RAILLY_SKILLS_REPO: base };
		writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
		console.log(`RAILLY_SKILLS_REPO => ${base}`);
	}

	// Without conventions, software-factory's implementation pass has no table
	// to read and improvises. Seed the shape; the repository fills the rows.
	const repoName = root.split(/[\\/]/).filter(Boolean).pop() || "project";
	const conventions = join(base, "cases", repoName, "conventions.md");
	if (!existsSync(conventions)) {
		mkdirSync(dirname(conventions), { recursive: true });
		writeFileSync(conventions, conventionsTemplate(repoName));
		console.log(`conventions seeded: ${conventions}`);
	}

	// Prove the redirection with Railly's own unmodified resolver.
	const resolver = join(MARKETPLACE_CLONE, "scripts", "resolve-source-root.mjs");
	if (existsSync(resolver)) {
		const r = spawnSync(process.execPath, [resolver], {
			encoding: "utf8",
			env: { ...process.env, RAILLY_SKILLS_REPO: base },
		});
		if (r.status === 0) console.log(`resolver agrees: ${r.stdout.trim()}`);
		else console.error(`resolver refused the scaffold: ${r.stderr.trim()}`);
	} else {
		console.error(`railly-skills clone not found at ${MARKETPLACE_CLONE}; scaffold written but unverified`);
	}

	console.log(`scaffold ok: ${base}`);
}

function conventionsTemplate(repoName) {
	return `# ${repoName} review conventions

Project overlay for the review-gate skill, and the repository half of the
\`implementation-routing\` skill. That skill is global and installed, not a file
in this repository, so it is named here rather than linked.

**Routing and precedence that hold everywhere live in \`implementation-routing\`,
not here.** Add a row below only to *override* it for this repository, or to
record something that is true of this repository alone. A global rule copied
into this file goes stale the day the global one changes, and nothing will say
so.

**Every entry names the case or review round that produced it.** An entry
without provenance carries no authority.

## Implementation-pass overrides

_Empty means: this repository routes exactly as \`implementation-routing\` says._

| Surface | This repository uses instead | Basis |
|---|---|---|

## Surface map

_A behavior change is not done until every surface that advertises it agrees.
List the source-to-surface pairs as they are discovered._

Provenance: empty until a review round fills it.

## Oracles

_What an implementation is checked against when the answer is not in this
repository: a specification, a reference implementation, a real producer._

Provenance: empty until a review round fills it.

## House norms

_This repository's own conventions. Empty until something is learned._

Provenance: empty until a review round fills it.
`;
}

const [cmd, arg] = process.argv.slice(2);
if (cmd === "scaffold") {
	scaffold(arg || process.cwd());
} else {
	console.error("usage: node scripts/railly-inrepo.mjs scaffold [project]");
	process.exit(1);
}
